-- PostgreSQL E2E Fixture — 03_create_tables.sql
-- Base tables with identity columns, generated (computed) columns, primary
-- keys, check constraints, and defaults.
-- Foreign keys are created in 04_create_foreign_keys.sql because they
-- reference tables that must exist first.
--
-- PostgreSQL type mapping from the MSSQL fixture:
--   IDENTITY(1,1)      -> GENERATED BY DEFAULT AS IDENTITY
--   NVARCHAR(n)        -> VARCHAR(n)
--   VARCHAR(n)         -> VARCHAR(n)
--   BIT                -> BOOLEAN
--   DATETIME2          -> TIMESTAMP
--   DECIMAL(p,s)       -> NUMERIC(p,s)
--   Computed column    -> GENERATED ALWAYS AS (expr) STORED

-- Customers
CREATE TABLE training.Customers (
    CustomerID   INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    CustomerCode VARCHAR(50) NOT NULL,
    FullName     VARCHAR(100) NOT NULL,
    Email        VARCHAR(150) NOT NULL,
    Phone        VARCHAR(20) NULL,
    City         VARCHAR(100) NULL,
    Status       VARCHAR(20) NOT NULL DEFAULT 'active',
    IsActive     BOOLEAN NOT NULL DEFAULT TRUE,
    CreatedAt    TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT PK_Customers PRIMARY KEY (CustomerID),
    CONSTRAINT UQ_Customers_Email UNIQUE (Email),
    CONSTRAINT CK_Customers_Email CHECK (LENGTH(TRIM(Email)) > 0),
    CONSTRAINT CK_Customers_Name CHECK (LENGTH(TRIM(FullName)) > 0)
);

-- Products
CREATE TABLE training.Products (
    ProductID  INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    SKU        VARCHAR(50) NOT NULL,
    Name       VARCHAR(200) NOT NULL,
    Category   VARCHAR(100) NOT NULL DEFAULT 'General',
    Price      NUMERIC(10,2) NOT NULL,
    StockQty   INT NOT NULL DEFAULT 0,
    IsActive   BOOLEAN NOT NULL DEFAULT TRUE,
    CreatedAt  TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT PK_Products PRIMARY KEY (ProductID),
    CONSTRAINT UQ_Products_SKU UNIQUE (SKU),
    CONSTRAINT CK_Products_Price CHECK (Price >= 0),
    CONSTRAINT CK_Products_Stock CHECK (StockQty >= 0)
);

-- Orders
CREATE TABLE training.Orders (
    OrderID      INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    OrderNumber  BIGINT NOT NULL,
    CustomerID   INT NOT NULL,
    TotalAmount  NUMERIC(10,2) NULL,
    OrderStatus  training.OrderStatus NOT NULL DEFAULT 'pending',
    OrderDate    TIMESTAMP NOT NULL DEFAULT NOW(),
    -- Generated (computed) column: timestamp one second ahead
    ModifiedAt   TIMESTAMP GENERATED ALWAYS AS (OrderDate + INTERVAL '1 second') STORED,
    CONSTRAINT PK_Orders PRIMARY KEY (OrderID),
    CONSTRAINT CK_Orders_Amount CHECK (TotalAmount >= 0 OR TotalAmount IS NULL)
);

-- OrderDetails
CREATE TABLE training.OrderDetails (
    DetailID   INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    OrderID    INT NOT NULL,
    ProductID  INT NOT NULL,
    Quantity   INT NOT NULL,
    UnitPrice  NUMERIC(10,2) NOT NULL,
    -- Generated (computed) column: line total
    LineTotal  NUMERIC(10,2) GENERATED ALWAYS AS (Quantity * UnitPrice) STORED,
    CONSTRAINT PK_OrderDetails PRIMARY KEY (DetailID),
    CONSTRAINT CK_OrderDetails_Quantity CHECK (Quantity > 0),
    CONSTRAINT CK_OrderDetails_UnitPrice CHECK (UnitPrice >= 0)
);

-- OrderAudit (populated by trigger on Orders insert)
CREATE TABLE training.OrderAudit (
    AuditID       INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    OrderID       INT NOT NULL,
    Action        VARCHAR(50) NOT NULL,
    AuditTimestamp TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT PK_OrderAudit PRIMARY KEY (AuditID)
);

-- PK_Name_Test — verifies that an explicitly named primary-key constraint
-- is discovered and reproduced on the target.
CREATE TABLE training.PK_Name_Test (
    TestID   INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    TestName VARCHAR(100) NOT NULL,
    CONSTRAINT PK_TestPrimaryKey PRIMARY KEY (TestID)
);

\echo 'Tables created: Customers, Products, Orders, OrderDetails, OrderAudit, PK_Name_Test.'
