-- PostgreSQL E2E Fixture — 12_create_partitions.sql
-- Range-partitioned table for orders by date.
-- PostgreSQL declarative partitioning splits the table into child partitions;
-- the connector's discover_partitions() enumerates them separately.

CREATE TABLE training.PartitionedOrders (
    PartitionID INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    OrderDate   DATE NOT NULL,
    Amount      NUMERIC(10,2) NOT NULL,
    Status      VARCHAR(50) NOT NULL DEFAULT 'pending',
    CONSTRAINT PK_PartitionedOrders PRIMARY KEY (PartitionID, OrderDate)
) PARTITION BY RANGE (OrderDate);

-- Partition for 2024 (before the 2025 boundary)
CREATE TABLE training.PartitionedOrders_2024
    PARTITION OF training.PartitionedOrders
    FOR VALUES FROM ('2024-01-01') TO ('2025-01-01');

-- Partition for 2025 H1
CREATE TABLE training.PartitionedOrders_2025_H1
    PARTITION OF training.PartitionedOrders
    FOR VALUES FROM ('2025-01-01') TO ('2025-07-01');

-- Partition for 2025 H2
CREATE TABLE training.PartitionedOrders_2025_H2
    PARTITION OF training.PartitionedOrders
    FOR VALUES FROM ('2025-07-01') TO ('2026-01-01');

-- Default partition for any other dates
CREATE TABLE training.PartitionedOrders_Default
    PARTITION OF training.PartitionedOrders
    DEFAULT;

\echo 'Partitioned table [training.PartitionedOrders] and 4 partitions created.'
