-- MySQL E2E Fixture — 03_create_tables.sql
-- Base tables with AUTO_INCREMENT, generated (computed) columns, primary
-- keys, check constraints, and defaults.
--
-- MySQL has no standalone user-defined ENUM type objects; the ENUM used
-- for order status is declared inline on the Orders table (the MySQL
-- equivalent of a custom enum type).
--
-- MySQL type mapping from the PostgreSQL fixture:
--   GENERATED BY DEFAULT AS IDENTITY  -> AUTO_INCREMENT
--   VARCHAR(n)                        -> VARCHAR(n)
--   BOOLEAN                           -> TINYINT(1)  (treated as boolean)
--   TIMESTAMP                         -> DATETIME
--   NUMERIC(p,s)                      -> DECIMAL(p,s)
--   Generated column (STORED)         -> AS (expr) STORED
--   CHECK (expr)                      -> CHECK (expr)

-- Customers
CREATE TABLE customers (
    customerid   INT AUTO_INCREMENT NOT NULL,
    customercode VARCHAR(50) NOT NULL,
    fullname     VARCHAR(100) NOT NULL,
    email        VARCHAR(150) NOT NULL,
    phone        VARCHAR(20) NULL,
    city         VARCHAR(100) NULL,
    status       VARCHAR(20) NOT NULL DEFAULT 'active',
    isactive     TINYINT(1) NOT NULL DEFAULT TRUE,
    createdat    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (customerid),
    UNIQUE KEY uq_customers_email (email),
    CONSTRAINT ck_customers_email CHECK (CHAR_LENGTH(TRIM(email)) > 0),
    CONSTRAINT ck_customers_name CHECK (CHAR_LENGTH(TRIM(fullname)) > 0)
);

-- Products
CREATE TABLE products (
    productid  INT AUTO_INCREMENT NOT NULL,
    sku        VARCHAR(50) NOT NULL,
    name       VARCHAR(200) NOT NULL,
    category   VARCHAR(100) NOT NULL DEFAULT 'General',
    price      DECIMAL(10,2) NOT NULL,
    stockqty   INT NOT NULL DEFAULT 0,
    isactive   TINYINT(1) NOT NULL DEFAULT TRUE,
    createdat  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (productid),
    UNIQUE KEY uq_products_sku (sku),
    CONSTRAINT ck_products_price CHECK (price >= 0),
    CONSTRAINT ck_products_stock CHECK (stockqty >= 0)
);

-- Orders
CREATE TABLE orders (
    orderid      INT AUTO_INCREMENT NOT NULL,
    ordernumber  BIGINT NOT NULL,
    customerid   INT NOT NULL,
    totalamount  DECIMAL(10,2) NULL,
    orderstatus  ENUM('pending','processing','shipped','delivered','cancelled')
                 NOT NULL DEFAULT 'pending',
    orderdate    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- Generated (computed) column: timestamp one second ahead
    modifiedat   DATETIME GENERATED ALWAYS AS (DATE_ADD(orderdate, INTERVAL 1 SECOND)) STORED,
    PRIMARY KEY (orderid),
    CONSTRAINT ck_orders_amount CHECK (totalamount >= 0 OR totalamount IS NULL),
    CONSTRAINT fk_orders_customers FOREIGN KEY (customerid) REFERENCES customers(customerid)
);

-- OrderDetails
CREATE TABLE orderdetails (
    detailid    INT AUTO_INCREMENT NOT NULL,
    orderid     INT NOT NULL,
    productid   INT NOT NULL,
    quantity    INT NOT NULL,
    unitprice   DECIMAL(10,2) NOT NULL,
    -- Generated (computed) column: line total
    linetotal   DECIMAL(10,2) GENERATED ALWAYS AS (quantity * unitprice) STORED,
    PRIMARY KEY (detailid),
    CONSTRAINT ck_orderdetails_quantity CHECK (quantity > 0),
    CONSTRAINT ck_orderdetails_unitprice CHECK (unitprice >= 0),
    CONSTRAINT fk_orderdetails_orders FOREIGN KEY (orderid) REFERENCES orders(orderid),
    CONSTRAINT fk_orderdetails_products FOREIGN KEY (productid) REFERENCES products(productid)
);

-- OrderAudit (populated by trigger on Orders insert)
CREATE TABLE orderaudit (
    auditid        INT AUTO_INCREMENT NOT NULL,
    orderid        INT NOT NULL,
    action         VARCHAR(50) NOT NULL,
    audittimestamp DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (auditid)
);

-- PK_Name_Test — verifies that an explicitly named primary-key constraint
-- is discovered and reproduced on the target.
CREATE TABLE pk_name_test (
    testid   INT AUTO_INCREMENT NOT NULL,
    testname VARCHAR(100) NOT NULL,
    CONSTRAINT pk_testprimarykey PRIMARY KEY (testid)
);

-- PartitionedOrders — MySQL native partitioning by range on orderdate.
-- MySQL RANGE partitioning requires single-value LESS THAN expressions,
-- so we use TO_DAYS() for date-based range partitioning.
CREATE TABLE partitionedorders (
    partitionid INT AUTO_INCREMENT NOT NULL,
    orderdate   DATE NOT NULL,
    amount      DECIMAL(10,2) NOT NULL,
    status      VARCHAR(50) NOT NULL DEFAULT 'pending',
    PRIMARY KEY (partitionid, orderdate)
) ENGINE=InnoDB
  PARTITION BY RANGE (TO_DAYS(orderdate)) (
    PARTITION p2024 VALUES LESS THAN (TO_DAYS('2025-01-01')),
    PARTITION p2025_h1 VALUES LESS THAN (TO_DAYS('2025-07-01')),
    PARTITION p2025_h2 VALUES LESS THAN (TO_DAYS('2026-01-01')),
    PARTITION p_default VALUES LESS THAN MAXVALUE
);

SELECT 'Tables created: customers, products, orders, orderdetails, orderaudit, pk_name_test, partitionedorders.' AS 'info';